// KlagonOrg payments relay — Moolre webhook receiver + donation charge endpoint.
//
// Secrets (wrangler secret put): SUPABASE_ANON_KEY, CALLBACK_KEY,
//   MOOLRE_USER, MOOLRE_PUBKEY, MOOLRE_WALLET, TURNSTILE_SECRET,
//   BREVO_API_KEY, CONFIRM_SECRET, FOLLOWUP_KEY, EMAIL_TEST_KEY.
//
// CONFIRM_SECRET is the shared secret that every confirm_*_by_ref RPC, plus
// create_course_order and create_sponsor_order, requires via the
// x-confirm-secret header. It is generated by
// supabase/migrations/20261003070000_course_payments.sql and must be copied out
// of public.app_secrets into this worker.

const MOOLRE_WALLET_CALLBACK_IP = "192.241.135.134";
const MOOLRE_API = "https://api.moolre.com/open/transact/payment";
const MOOLRE_STATUS_API = "https://api.moolre.com/open/transact/status";
const TURNSTILE_VERIFY = "https://challenges.cloudflare.com/turnstile/v0/siteverify";

const PAID_SIGNALS = new Set(["success", "successful", "completed", "paid", "1"]);
const FAILED_SIGNALS = new Set(["failed", "failure", "cancelled", "canceled", "rejected", "0"]);

// Browsers allowed to call the charge endpoint (the site + its previews).
function corsHeaders(origin) {
  const allowed =
    origin === "https://klagon.org" ||
    origin === "https://www.klagon.org" ||
    (typeof origin === "string" && origin.endsWith(".klagon-org.pages.dev"));
  return {
    "Content-Type": "application/json",
    ...(allowed ? { "Access-Control-Allow-Origin": origin, Vary: "Origin" } : {}),
    "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
    "Access-Control-Allow-Headers": "Authorization, Content-Type",
  };
}

function json(obj, status = 200, origin = "") {
  return new Response(JSON.stringify(obj), { status, headers: corsHeaders(origin) });
}

const CHANNELS = { mtn: "13", telecel: "6", at: "7" };

function normalizeGhPhone(raw) {
  const digits = String(raw ?? "").replace(/[\s-]/g, "");
  if (/^0\d{9}$/.test(digits)) return digits;
  const m = digits.match(/^\+233(\d{9})$/);
  if (m) return `0${m[1]}`;
  return null;
}

function sbHeaders(env) {
  return {
    apikey: env.SUPABASE_ANON_KEY,
    Authorization: `Bearer ${env.SUPABASE_ANON_KEY}`,
    "Content-Type": "application/json",
  };
}

function sbRpc(env, fn, body) {
  return fetch(`${env.SUPABASE_URL}/rest/v1/rpc/${fn}`, {
    method: "POST",
    headers: sbHeaders(env),
    body: JSON.stringify(body),
  });
}

// Payment mutating RPCs require a worker-only shared secret; the guard lives in
// the database (confirm_secret_ok). Reads that grant nothing use sbRpc.
function sbRpcSigned(env, fn, body) {
  return fetch(`${env.SUPABASE_URL}/rest/v1/rpc/${fn}`, {
    method: "POST",
    headers: { ...sbHeaders(env), "x-confirm-secret": env.CONFIRM_SECRET ?? "" },
    body: JSON.stringify(body),
  });
}

// Human check, enforced server-side (H2): every money-moving charge requires
// a Turnstile token the browser obtained from the widget. Client-only checks
// stop honest users; this stops bots calling the worker directly.
async function verifyTurnstileToken(env, token) {
  if (!env.TURNSTILE_SECRET || !token) return false;
  try {
    const res = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({ secret: env.TURNSTILE_SECRET, response: String(token) }),
    });
    const body = await res.json();
    return body?.success === true;
  } catch {
    return false;
  }
}

// Best-effort per-IP fixed-window limiter (H3). Isolates reset it, so this
// blunts bursts rather than guaranteeing caps; Cloudflare dashboard rate
// rules remain the hard boundary.
const RATE_BUCKETS = new Map();
function rateLimited(ip, route, limit, windowMs) {
  const now = Date.now();
  const key = `${ip}|${route}`;
  let bucket = RATE_BUCKETS.get(key);
  if (!bucket || now - bucket.start > windowMs) {
    bucket = { start: now, count: 0 };
    RATE_BUCKETS.set(key, bucket);
  }
  bucket.count += 1;
  if (RATE_BUCKETS.size > 5000) RATE_BUCKETS.clear();
  return bucket.count > limit;
}

function clientIp(request) {
  return request.headers.get("CF-Connecting-IP") ?? "unknown";
}

async function requireHuman(request, env, origin, input) {
  const token = input?.turnstile_token;
  if (!token || !(await verifyTurnstileToken(env, token))) {
    return json({ error: "Please complete the human check and try again." }, 403, origin);
  }
  return null;
}

function requireRate(request, route, limit, windowMs) {
  if (rateLimited(clientIp(request), route, limit, windowMs)) {
    return json({ error: "Too many requests. Please wait a minute and try again." }, 429);
  }
  return null;
}

// Resolve a signed-in member from the browser's Supabase access token. Used so
// a course purchase always attaches to a real auth.uid() the caller cannot
// spoof by naming someone else.
async function authUserId(env, request) {
  const auth = request.headers.get("Authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7).trim() : "";
  if (!token) return null;
  try {
    const res = await fetch(`${env.SUPABASE_URL}/auth/v1/user`, {
      headers: { apikey: env.SUPABASE_ANON_KEY, Authorization: `Bearer ${token}` },
    });
    if (!res.ok) return null;
    const user = await res.json();
    return typeof user?.id === "string" ? user.id : null;
  } catch {
    return null;
  }
}

// Ref prefixes route the single Moolre callback to the right order table.
// Donation refs are the bare KLG- prefix with no sub-prefix.
const KLG_REF_PREFIX = "KLG-";
const BOOST_REF_PREFIX = "KLG-B-";
const SPONSOR_REF_PREFIX = "KLG-S-";
const COURSE_REF_PREFIX = "KLG-C-";

// Self-serve sponsorship tiers. 'strategic' is bespoke (enquire off-platform).
const SELF_SERVE_SPONSOR_TIERS = new Set(["community", "growth", "talent", "digital"]);

const failRow = (env, ref) =>
  sbRpcSigned(env, "confirm_donation_by_ref", { p_ref: ref, p_status: "failed" }).catch(() => null);

const failBoostRow = (env, ref) =>
  sbRpcSigned(env, "confirm_boost_payment_by_ref", { p_ref: ref, p_status: "failed" }).catch(() => null);

const failSponsorRow = (env, ref) =>
  sbRpcSigned(env, "confirm_sponsor_payment_by_ref", { p_ref: ref, p_status: "failed" }).catch(() => null);

const failCourseRow = (env, ref) =>
  sbRpcSigned(env, "confirm_course_payment_by_ref", { p_ref: ref, p_status: "failed" }).catch(() => null);

const BREVO_API = "https://api.brevo.com/v3/smtp/email";
const BREVO_FROM = { name: "KlagonOrg Team", email: "hello@klagon.org" };

async function brevoSend(env, to, subject, html) {
  if (!env.BREVO_API_KEY || !to?.length) return null;
  const res = await fetch(BREVO_API, {
    method: "POST",
    headers: {
      "api-key": env.BREVO_API_KEY,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({ sender: BREVO_FROM, to, subject, htmlContent: html }),
  });
  return res.json();
}

async function sendDonationEmails(env, ref) {
  // Signed: get_donation_sendable carries payer PII and requires the
  // worker-only confirm secret (C1: anon callers get 'forbidden').
  const res = await sbRpcSigned(env, "get_donation_sendable", { p_ref: ref });
  const row = res.ok ? (await res.json())[0] : null;
  if (!row) return;

  const amount = Number(row.amount_ghs ?? 0).toFixed(2);
  const rowName = String(row.full_name || "").trim();
  const name = rowName ? rowName.split(" ")[0] : "Friend";

  if (row.email) {
    await brevoSend(
      env,
      [{ email: String(row.email).trim(), name }],
      `Your KlagonOrg donation of GH₵${amount}`,
      `<p>Hi ${name},</p><p>Thank you for your donation of <strong>GH\u00a5${amount}</strong> to KlagonOrg (ref <code>${ref}</code>).</p><p>Your support helps advance our mission. Follow progress at <a href="https://klagon.org">klagon.org</a>.</p>`
    ).catch(() => null);
  }

  await brevoSend(
    env,
    [{ email: "klagonorg@gmail.com", name: "KlagonOrg Admin" }],
    `New donation received — GH₵${amount}`,
    `<p>Reference: <code>${ref}</code></p><p>Name: ${rowName || "Anonymous"}</p><p>Amount: GH\u00a5${amount}</p><p>Email: ${row.email || "—"}</p>`
  ).catch(() => null);
}

async function sendBoostEmails(env, ref) {
  const res = await sbRpcSigned(env, "get_boost_sendable", { p_ref: ref });
  const row = res.ok ? (await res.json())[0] : null;
  if (!row) return;

  const amount = Number(row.amount_ghs ?? 0).toFixed(2);
  const payerEmail = row.payer_email ? String(row.payer_email).trim() : "";
  if (payerEmail && payerEmail.includes("@")) {
    await brevoSend(
      env,
      [{ email: payerEmail, name: "KLAGON seller" }],
      `Boost confirmed — featured for ${row.days} days`,
      `<p>Hi,</p><p>Payment of <strong>GH₵${amount}</strong> confirmed (ref <code>${ref}</code>). Your listing <strong>${row.post_title ?? "—"}</strong> is featured as <strong>${row.tier}</strong> for ${row.days} days.</p>`
    ).catch(() => null);
  }
  await brevoSend(
    env,
    [{ email: "klagonorg@gmail.com", name: "KlagonOrg Admin" }],
    `Boost paid — GH₵${amount}`,
    `<p>Reference: <code>${ref}</code></p><p>Listing: ${row.post_title ?? "—"}</p><p>Tier: ${row.tier} (${row.days} days)</p><p>Amount: GH\u00a5${amount}</p><p>Phone: ${row.payer_phone ?? "—"}</p>`
  ).catch(() => null);
}

async function sendSponsorEmails(env, ref) {
  const res = await sbRpcSigned(env, "get_sponsor_sendable", { p_ref: ref });
  const row = res.ok ? (await res.json())[0] : null;
  if (!row) return;

  const amount = Number(row.amount_ghs ?? 0).toFixed(2);
  const org = String(row.org_name || row.full_name || "").trim() || "your business";
  const name = firstTokenName(row.full_name);

  if (row.email) {
    await brevoSend(
      env,
      [{ email: String(row.email).trim(), name }],
      `Sponsorship received — GH₵${amount}`,
      `<p>Hi ${name},</p><p>Thank you for partnering with KlagonOrg. We received <strong>GH\u00a5${amount}</strong> for the <strong>${row.tier}</strong> tier (${row.months} month${row.months > 1 ? "s" : ""}, ref <code>${ref}</code>).</p><p>Our partnerships team will set up ${org}'s sponsor profile and activate your benefits shortly.</p>`
    ).catch(() => null);
  }

  await brevoSend(
    env,
    [{ email: "klagonorg@gmail.com", name: "KlagonOrg Admin" }],
    `New sponsorship paid — GH₵${amount}`,
    `<p>Reference: <code>${ref}</code></p><p>Business: ${org}</p><p>Contact: ${row.full_name ?? "—"}</p><p>Email: ${row.email || "—"}</p><p>Phone: ${row.payer_phone ?? "—"}</p><p>Tier: ${row.tier} (${row.months} month${row.months > 1 ? "s" : ""})</p><p>Amount: GH\u00a5${amount}</p><p>Promote from the admin sponsors queue.</p>`
  ).catch(() => null);
}

async function sendCourseEmails(env, ref) {
  const res = await sbRpcSigned(env, "get_course_sendable", { p_ref: ref });
  const row = res.ok ? (await res.json())[0] : null;
  if (!row) return;

  const amount = Number(row.amount_ghs ?? 0).toFixed(2);
  const name = firstTokenName(row.member_name);
  const courseTitle = row.course_title ?? "your course";

  if (row.member_email) {
    await brevoSend(
      env,
      [{ email: String(row.member_email).trim(), name }],
      `Your course access — ${courseTitle}`,
      `<p>Hi ${name},</p><p>Thank you! Your payment of <strong>GH\u00a5${amount}</strong> for <strong>${courseTitle}</strong> is confirmed (ref <code>${ref}</code>).</p><p>Lifetime access is now unlocked in your <a href="https://klagon.org/learning">learning dashboard</a>.</p>`
    ).catch(() => null);
  }

  await brevoSend(
    env,
    [{ email: "klagonorg@gmail.com", name: "KlagonOrg Admin" }],
    `Course purchase — GH₵${amount}`,
    `<p>Reference: <code>${ref}</code></p><p>Course: ${courseTitle}</p><p>Buyer: ${row.member_name ?? "—"} (${row.member_email ?? "—"})</p><p>Phone: ${row.payer_phone ?? "—"}</p><p>Amount: GH\u00a5${amount}</p>`
  ).catch(() => null);
}

// ---------- visitor auto-replies (lead-gen Phase 3) ----------
// DEPLOY: `npx wrangler deploy` from workers/moolre (needs Cloudflare auth),
// then `wrangler secret put FOLLOWUP_KEY` (any random string) alongside the
// existing BREVO_API_KEY. Delivery per event via Supabase Dashboard →
// Database → Webhooks: POST to /api/followup/autoreply on INSERT into
// donations / inkind_offers / contact_messages / sponsor_applications /
// mentor_applications / volunteer_applications with HTTP headers
// {"x-followup-key": "<FOLLOWUP_KEY>"} and a JSON body of
// {"kind": "<template>", "to": "<email>", "name": "...", "ref": "..."}.
// Until wired, the site works unchanged (in-app + manual WhatsApp only).
const AUTOREPLY_TEMPLATES = {
  pledge: {
    subject: (name) => `Medase ${name}! Your KLAGON.org pledge is in 🙏`,
    html: (name, ref) =>
      `<p>Hi ${name},</p><p>Medase — your pledge${ref ? ` (ref <code>${ref}</code>)` : ""} is recorded. We call or WhatsApp you within 24 hours to complete it by MoMo. Every cedi funds KLAGON.org programs.</p><p><a href="https://klagon.org/impact">See what your gift builds →</a></p>`,
  },
  inkind: {
    subject: (name) => `Medase ${name}! Your gift offer is in 🎁`,
    html: (name) =>
      `<p>Hi ${name},</p><p>Medase for offering your gift to Klagon! Our team replies within 48 hours to arrange collection or next steps.</p><p><a href="https://klagon.org/impact">See what gifts like yours build →</a></p>`,
  },
  contact: {
    subject: (name) => `We got your message, ${name} ✉️`,
    html: (name) =>
      `<p>Hi ${name},</p><p>Thanks for writing to KLAGON.org — a real person replies within 24 hours. Anything urgent, WhatsApp 026 870 8895.</p>`,
  },
  sponsor: {
    subject: (name) => `Medase ${name} — your sponsorship enquiry is in 🤝`,
    html: (name) =>
      `<p>Hi ${name},</p><p>Thanks for your interest in partnering with KLAGON.org. Our partnerships team finalizes details within 2 business days.</p><p><a href="https://klagon.org/impact">Our impact, in live numbers →</a></p>`,
  },
  mentor: {
    subject: (name) => `Medase ${name} — mentor application received 🎉`,
    html: (name) =>
      `<p>Hi ${name},</p><p>Your KLAGON.org mentor application is under review — we confirm within 48 hours. Medase for stepping up for Klagon's youth.</p>`,
  },
  volunteer: {
    subject: (name) => `Medase ${name} — volunteer application received 🙋`,
    html: (name) =>
      `<p>Hi ${name},</p><p>Your volunteer application is under review (ID verification first). We confirm within a few days — track it any time in your dashboard.</p>`,
  },
  newsletter: {
    subject: () => `Welcome to KLAGON.org news 📰`,
    html: () =>
      `<p>You're on the list — community news and new listings, once a month, no spam.</p><p>Meanwhile: <a href="https://klagon.org/learning">learn something free</a> or <a href="https://klagon.org/volunteer">volunteer</a>.</p>`,
  },
};

function firstTokenName(name) {
  const n = String(name || "").trim().split(" ")[0];
  return n || "Friend";
}

async function handleAutoreply(request, env) {
  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: "bad-json" }, 400);
  }
  if (!env.FOLLOWUP_KEY || request.headers.get("x-followup-key") !== env.FOLLOWUP_KEY) {
    return json({ error: "forbidden" }, 403);
  }
  const tpl = AUTOREPLY_TEMPLATES[body.kind];
  const to = String(body.to || "").trim();
  if (!tpl || !to) return json({ error: "unknown-kind" }, 400);
  const name = firstTokenName(body.name);
  const result = await brevoSend(
    env,
    [{ email: to, name }],
    tpl.subject(name),
    tpl.html(name, body.ref)
  ).catch(() => null);
  return json({ ok: true, result });
}

async function moolreCollect(env, { channel, payer, amount, ref, network, otp }) {
  const res = await fetch(MOOLRE_API, {
    method: "POST",
    headers: {
      "X-API-USER": env.MOOLRE_USER,
      "X-API-PUBKEY": env.MOOLRE_PUBKEY,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      type: 1,
      channel,
      currency: "GHS",
      payer,
      amount: String(amount),
      externalref: ref,
      ...(otp ? { otpcode: String(otp) } : {}),
      reference: `KlagonOrg ${orderKind(ref)} ${ref}`,
      accountnumber: env.MOOLRE_WALLET,
    }),
  });
  return res.json();
}

// Resolve a ref to its order kind. Throws on anything that is not a Klagon ref:
// every prefix we mint starts with KLG-, so a ref that matches none of them is a
// bug or a probe. This used to fall through to "donation", which meant a
// mistyped or future-provider prefix would settle against the donations table
// instead of erroring — silent, and it would have misrouted card payments as
// soon as a second provider landed.
function orderKind(ref) {
  if (ref.startsWith(BOOST_REF_PREFIX)) return "boost";
  if (ref.startsWith(SPONSOR_REF_PREFIX)) return "sponsor";
  if (ref.startsWith(COURSE_REF_PREFIX)) return "course";
  if (ref.startsWith(KLG_REF_PREFIX)) return "donation";
  throw new Error("unrecognised order reference");
}

function confirmFnFor(kind) {
  return kind === "boost"
    ? "confirm_boost_payment_by_ref"
    : kind === "sponsor"
    ? "confirm_sponsor_payment_by_ref"
    : kind === "course"
    ? "confirm_course_payment_by_ref"
    : "confirm_donation_by_ref";
}

// Ask Moolre for the final status of a reference. The callback is the primary
// settlement path, but webhooks get dropped; this is the reconciliation path so
// a missed callback can never strand an order as pending forever.
async function moolreStatus(env, ref) {
  const res = await fetch(MOOLRE_STATUS_API, {
    method: "POST",
    headers: {
      "X-API-USER": env.MOOLRE_USER,
      "X-API-PUBKEY": env.MOOLRE_PUBKEY,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ type: 1, idtype: 1, id: ref, accountnumber: env.MOOLRE_WALLET }),
  });
  return res.json();
}

function moolreOutcome(payload) {
  const code = String(payload?.code ?? "");
  const message = String(payload?.message ?? "");
  const tx = payload?.data?.txstatus;
  const txStr = String(tx ?? "").toLowerCase();
  if (code === "SS01" || tx === 1 || PAID_SIGNALS.has(txStr) || /success/i.test(message)) {
    return "paid";
  }
  if (FAILED_SIGNALS.has(txStr) || tx === -1 || /fail|cancel|reject|declin/i.test(message)) {
    return "failed";
  }
  return "pending";
}

// Returns the order kind and whether this call actually moved a pending row.
// The confirm RPCs answer that now; when they returned void the worker could not
// tell "just settled" from "already settled long ago", so it reported success
// and sent receipts for refs it had never seen.
async function settleOrder(env, ref, status) {
  const kind = orderKind(ref);
  const res = await sbRpcSigned(env, confirmFnFor(kind), { p_ref: ref, p_status: status });
  if (!res.ok) throw new Error((await res.text()).slice(0, 200));
  const moved = (await res.json()) === true;
  return { kind, moved };
}

async function handlePaymentStatus(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  const statusLimited = requireRate(request, "payments-status", 30, 60_000);
  if (statusLimited) return statusLimited;

  let ref = "";
  if (request.method === "GET") {
    ref = String(new URL(request.url).searchParams.get("ref") ?? "").trim();
  } else {
  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send ref and otp." }, 400, origin);
  }
    ref = String(input?.ref ?? "").trim();
  }
  if (!ref) return json({ error: "Send a ref." }, 400, origin);

  // Resolve the order type before spending an upstream call. An unrecognised
  // ref is a client error, not something to settle.
  let kind;
  try {
    kind = orderKind(ref);
  } catch {
    return json({ error: "Unknown payment reference." }, 400, origin);
  }

  if (!env.MOOLRE_USER || !env.MOOLRE_PUBKEY || !env.MOOLRE_WALLET) {
    return json({ error: "Online payments are not switched on yet." }, 503, origin);
  }

  let payload;
  try {
    payload = await moolreStatus(env, ref);
  } catch {
    return json({ error: "Payment service unreachable." }, 502, origin);
  }

  const outcome = moolreOutcome(payload);
  let settled = false;
  if (outcome !== "pending") {
    try {
      const { moved } = await settleOrder(env, ref, outcome);
      settled = moved;
      if (moved && outcome === "paid") {
        if (kind === "boost") await sendBoostEmails(env, ref).catch(() => null);
        else if (kind === "sponsor") await sendSponsorEmails(env, ref).catch(() => null);
        else if (kind === "course") await sendCourseEmails(env, ref).catch(() => null);
        else await sendDonationEmails(env, ref).catch(() => null);
      }
    } catch {
      return json({ error: "supabase-update-failed", provider: outcome }, 502, origin);
    }
  }

  // The raw provider code and message are deliberately not echoed: this route is
  // unauthenticated, and they leak Moolre's internal vocabulary to anyone who
  // can reach the worker.
  return json({ ok: true, ref, kind, provider: outcome, settled }, 200, origin);
}

async function handleCharge(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send amount, phone and network." }, 400, origin);
  }

  const limited = requireRate(request, "donations-charge", 10, 60_000);
  if (limited) return limited;
  const human = await requireHuman(request, env, origin, input);
  if (human) return human;

  const amount = Number(input?.amount_ghs);
  if (!Number.isFinite(amount) || amount <= 0) {
    return json({ error: "Enter a valid amount." }, 400, origin);
  }
  const channel = CHANNELS[String(input?.network ?? "").toLowerCase()];
  if (!channel) {
    return json({ error: "Choose MTN, Telecel or AT." }, 400, origin);
  }
  const payer = normalizeGhPhone(input?.phone);
  if (!payer) {
    return json({ error: "Enter a valid 10-digit Ghana phone number." }, 400, origin);
  }

  // Walk bookings (tier_id "tour:<walk-id>") re-derive the total server-side
  // from the mirrored price table, so a tampered client amount can never buy
  // a GH₵3,000 walk for GH₵1. Pure donations keep the donor-chosen amount.
  // Mirror of src/lib/tours.ts TOUR_WALKS — update both together.
  const TOUR_PRICES = {
    "wetland-market-walk": 750,
    "dawn-birding": 350,
    "klagon-by-night": 450,
  };
  let walkMeta = null;
  const tierId = String(input?.tier_id ?? "");
  if (tierId.startsWith("tour:")) {
    const walkId = tierId.slice("tour:".length);
    const perPerson = TOUR_PRICES[walkId];
    const w = input?.walk && typeof input.walk === "object" ? input.walk : null;
    const guests = Math.min(10, Math.max(4, Number(w?.guests) || 0));
    const date = typeof w?.date === "string" ? w.date.slice(0, 10) : "";
    if (perPerson == null || !guests || !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
      return json({ error: "That walk, party size or date is not bookable here. Please start again." }, 409, origin);
    }
    const expected = perPerson * guests;
    if (amount !== expected) {
      return json({ error: `That walk costs GH₵${expected.toLocaleString()} for ${guests} guests. Please start again.` }, 409, origin);
    }
    walkMeta = { walk_id: walkId, guests, date };
  }

  if (!env.MOOLRE_USER || !env.MOOLRE_PUBKEY || !env.MOOLRE_WALLET) {
    return json({ error: "Online payments are not switched on yet. Please try again later." }, 503, origin);
  }

  const ref = `KLG-${Date.now().toString(36)}-${crypto.randomUUID().slice(0, 8)}`.toUpperCase();

  // 1) Pending row first (anon insert allowed for status='pending' by RLS).
  try {
    const res = await fetch(`${env.SUPABASE_URL}/rest/v1/donations`, {
      method: "POST",
      headers: {
        apikey: env.SUPABASE_ANON_KEY,
        Authorization: `Bearer ${env.SUPABASE_ANON_KEY}`,
        "Content-Type": "application/json",
        Prefer: "return=minimal",
      },
      body: JSON.stringify({
        amount_ghs: amount,
        tier_id: input?.tier_id ?? null,
        full_name: input?.full_name || null,
        phone: payer,
        email: input?.email || null,
        status: "pending",
        provider: "moolre",
        provider_ref: ref,
        metadata: { network: String(input.network).toLowerCase(), ...(walkMeta ? { walk: walkMeta } : {}) },
      }),
    });
    if (!res.ok) {
      return json({ error: "Could not start your donation. Please try again." }, 502, origin);
    }
  } catch {
    return json({ error: "Could not start your donation. Please try again." }, 502, origin);
  }

  // 2) Fire the payment request.
  let moolre;
  try {
    moolre = await moolreCollect(env, { channel, payer, amount, ref, network: input.network });
  } catch {
    await failRow(env, ref);
    return json({ error: "Payment service unreachable. Please try again." }, 502, origin);
  }

  const code = moolre?.code ? String(moolre.code) : "";
  if (moolre?.status == 1) {
    if (code === "TR099") {
      return json({ ok: true, ref, payer, message: "prompt-sent" }, 200, origin);
    }
    if (code === "TP14") {
      // OTP required: keep the row pending; the donor enters the SMS code next.
      return json({ ok: true, ref, payer, otp_required: true, message: "otp-required" }, 200, origin);
    }
    // Any other success-family code (e.g. TP17) = initiated; callback settles it.
    return json({ ok: true, ref, payer, message: "initiated" }, 200, origin);
  }

  await failRow(env, ref);
  return json(
    {
      error: moolre?.message ? String(moolre.message) : "Payment request failed. Please try again.",
      code,
    },
    502,
    origin
  );
}

async function handleConfirm(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send ref and otp." }, 400, origin);
  }

  const ref = String(input?.ref ?? "").trim();
  const otp = String(input?.otp ?? "").replace(/\s/g, "");
  if (!ref || otp.length < 4) {
    return json({ error: "Enter the full OTP from the SMS." }, 400, origin);
  }
  const donationConfirmLimited = requireRate(request, "donations-confirm", 20, 60_000);
  if (donationConfirmLimited) return donationConfirmLimited;
  // M2: re-submit the amount/phone/network from our own order row, never the
  // client's — same pattern as the boost/sponsor/course confirms.
  const orderRes = await sbRpcSigned(env, "get_donation_sendable", { p_ref: ref });
  const order = orderRes.ok ? (await orderRes.json())[0] : null;
  if (!order) {
    return json({ error: "We can't find that payment request. Please start again." }, 404, origin);
  }
  const amount = Number(order.amount_ghs);
  const channel = CHANNELS[String(order.network ?? "").toLowerCase()] ?? "13";
  const payer = normalizeGhPhone(order.phone) ?? order.phone;
  if (!Number.isFinite(amount) || amount <= 0 || !payer) {
    return json({ error: "That payment request is incomplete. Please start again." }, 409, origin);
  }

  let moolre;
  try {
    moolre = await moolreCollect(env, {
      channel,
      payer,
      amount,
      ref,
      network: order.network,
      otp,
    });
  } catch {
    return json({ error: "Payment service unreachable. Please try again." }, 502, origin);
  }

  const code = moolre?.code ? String(moolre.code) : "";
  if (moolre?.status == 1) {
    return json({ ok: true, ref, message: code === "TR099" ? "prompt-sent" : "initiated" }, 200, origin);
  }

  return json(
    {
      error: moolre?.message ? String(moolre.message) : "Verification failed. Check the code and try again.",
      code,
    },
    400,
    origin
  );
}

// ---------- paid boosts ----------
// Boosts charge a server-derived fee (boost_quote), never a client amount.
// Orders live in boost_payments; confirm_boost_payment_by_ref flips them and
// applies the placement, so the browser never touches boost_until.
async function handleBoostCharge(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send a listing, phone and network." }, 400, origin);
  }

  const boostLimited = requireRate(request, "boosts-charge", 10, 60_000);
  if (boostLimited) return boostLimited;
  const boostHuman = await requireHuman(request, env, origin, input);
  if (boostHuman) return boostHuman;

  const postId = String(input?.post_id ?? "").trim();
  if (!/^[0-9a-f-]{36}$/i.test(postId)) {
    return json({ error: "Pick a listing to feature." }, 400, origin);
  }
  const channel = CHANNELS[String(input?.network ?? "").toLowerCase()];
  if (!channel) {
    return json({ error: "Choose MTN, Telecel or AT." }, 400, origin);
  }
  const payer = normalizeGhPhone(input?.phone);
  if (!payer) {
    return json({ error: "Enter a valid 10-digit Ghana phone number." }, 400, origin);
  }
  const receiptEmail =
    typeof input?.email === "string" && input.email.includes("@")
      ? input.email.trim().slice(0, 160)
      : null;

  if (!env.MOOLRE_USER || !env.MOOLRE_PUBKEY || !env.MOOLRE_WALLET) {
    return json({ error: "Online payments are not switched on yet. Please try again later." }, 503, origin);
  }

  // The price is whatever the database says; an ineligible listing returns none.
  let quote = null;
  try {
    const res = await sbRpc(env, "boost_quote", { p_post_id: postId });
    if (res.ok) {
      const rows = await res.json();
      quote = Array.isArray(rows) ? rows[0] : null;
    }
  } catch {
    quote = null;
  }
  if (!quote) {
    return json({ error: "This listing can’t be featured right now." }, 409, origin);
  }

  const amount = Number(quote.fee_ghs);
  const days = Number(quote.days);
  const tier = String(quote.tier);

  const ref = `${BOOST_REF_PREFIX}${Date.now().toString(36)}-${crypto.randomUUID().slice(0, 8)}`.toUpperCase();

  // 1) Pending order first (anon insert allowed for status='pending' by RLS).
  try {
    const res = await fetch(`${env.SUPABASE_URL}/rest/v1/boost_payments`, {
      method: "POST",
      headers: { ...sbHeaders(env), Prefer: "return=minimal" },
      body: JSON.stringify({
        post_id: postId,
        tier,
        amount_ghs: amount,
        days,
        status: "pending",
        provider: "moolre",
        provider_ref: ref,
        payer_phone: payer,
        network: String(input.network).toLowerCase(),
        metadata: receiptEmail ? { email: receiptEmail } : {},
      }),
    });
    if (!res.ok) {
      return json({ error: "Could not start your boost. Please try again." }, 502, origin);
    }
  } catch {
    return json({ error: "Could not start your boost. Please try again." }, 502, origin);
  }

  // 2) Fire the payment request.
  let moolre;
  try {
    moolre = await moolreCollect(env, { channel, payer, amount, ref, network: input.network });
  } catch {
    await failBoostRow(env, ref);
    return json({ error: "Payment service unreachable. Please try again." }, 502, origin);
  }

  const code = moolre?.code ? String(moolre.code) : "";
  if (moolre?.status == 1) {
    if (code === "TP14") {
      return json({ ok: true, ref, payer, otp_required: true, amount_ghs: amount, days, tier, message: "otp-required" }, 200, origin);
    }
    return json(
      { ok: true, ref, payer, amount_ghs: amount, days, tier, message: code === "TR099" ? "prompt-sent" : "initiated" },
      200,
      origin
    );
  }

  await failBoostRow(env, ref);
  return json(
    {
      error: moolre?.message ? String(moolre.message) : "Payment request failed. Please try again.",
      code,
    },
    502,
    origin
  );
}

async function handleBoostConfirm(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send ref and otp." }, 400, origin);
  }

  const ref = String(input?.ref ?? "").trim();
  const otp = String(input?.otp ?? "").replace(/\s/g, "");
  if (!ref || otp.length < 4) {
    return json({ error: "Enter the full OTP from the SMS." }, 400, origin);
  }

  // Re-submit the amount from our own order row, never the client's.
  let order = null;
  try {
    const res = await sbRpcSigned(env, "get_boost_sendable", { p_ref: ref });
    if (res.ok) {
      const rows = await res.json();
      order = Array.isArray(rows) ? rows[0] : null;
    }
  } catch {
    order = null;
  }
  const boostConfirmLimited = requireRate(request, "boosts-confirm", 20, 60_000);
  if (boostConfirmLimited) return boostConfirmLimited;
  if (!order || !Number.isFinite(Number(order.amount_ghs))) {
    return json({ error: "We could not find that order. Please start again." }, 404, origin);
  }

  const amount = Number(order.amount_ghs);
  const channel = CHANNELS[String(input?.network ?? "").toLowerCase()] ?? "13";
  const payer = normalizeGhPhone(input?.phone) ?? input?.phone;

  let moolre;
  try {
    moolre = await moolreCollect(env, { channel, payer, amount, ref, network: input?.network, otp });
  } catch {
    return json({ error: "Payment service unreachable. Please try again." }, 502, origin);
  }

  const code = moolre?.code ? String(moolre.code) : "";
  if (moolre?.status == 1) {
    return json({ ok: true, ref, message: code === "TR099" ? "prompt-sent" : "initiated" }, 200, origin);
  }

  return json(
    {
      error: moolre?.message ? String(moolre.message) : "Verification failed. Check the code and try again.",
      code,
    },
    400,
    origin
  );
}

// ---------- paid sponsorships ----------
// Sponsorships charge a server-derived fee (sponsor_quote), never a client
// amount, and record an application + order. On payment the order is marked
// paid; an admin promotes the partner from the paid queue (no auto-promote).
async function handleSponsorCharge(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send a tier, phone and network." }, 400, origin);
  }

  const sponsorLimited = requireRate(request, "sponsors-charge", 10, 60_000);
  if (sponsorLimited) return sponsorLimited;
  const sponsorHuman = await requireHuman(request, env, origin, input);
  if (sponsorHuman) return sponsorHuman;

  const tier = String(input?.tier ?? "").trim().toLowerCase();
  if (!SELF_SERVE_SPONSOR_TIERS.has(tier)) {
    return json({ error: "Choose a partnership tier." }, 400, origin);
  }
  const fullName = String(input?.full_name ?? "").trim();
  if (!fullName) {
    return json({ error: "Enter your name or organisation." }, 400, origin);
  }
  const channel = CHANNELS[String(input?.network ?? "").toLowerCase()];
  if (!channel) {
    return json({ error: "Choose MTN, Telecel or AT." }, 400, origin);
  }
  const payer = normalizeGhPhone(input?.phone);
  if (!payer) {
    return json({ error: "Enter a valid 10-digit Ghana phone number." }, 400, origin);
  }

  if (!env.MOOLRE_USER || !env.MOOLRE_PUBKEY || !env.MOOLRE_WALLET) {
    return json({ error: "Online payments are not switched on yet. Please try again later." }, 503, origin);
  }
  // create_sponsor_order is signed, so fail fast here rather than letting a
  // missing secret surface as "tier not available" below.
  if (!env.CONFIRM_SECRET) {
    return json({ error: "Online payments are not switched on yet. Please try again later." }, 503, origin);
  }

  const ref = `${SPONSOR_REF_PREFIX}${Date.now().toString(36)}-${crypto.randomUUID().slice(0, 8)}`.toUpperCase();

  // Quote + record the application and the pending order atomically. The RPC
  // derives the price itself and returns the authoritative amount; a bespoke or
  // unknown tier raises, so the browser can never name its own fee. Signed, like
  // create_course_order: this is a write reachable with the public anon key.
  let order = null;
  try {
    const res = await sbRpcSigned(env, "create_sponsor_order", {
      p_tier: tier,
      p_full_name: fullName,
      p_org_name: String(input?.org_name ?? "").trim() || null,
      p_email: String(input?.email ?? "").trim() || null,
      p_phone: payer,
      p_network: String(input.network).toLowerCase(),
      p_provider_ref: ref,
      p_message: input?.message || null,
    });
    if (res.ok) {
      const rows = await res.json();
      order = Array.isArray(rows) ? rows[0] : null;
    }
  } catch {
    order = null;
  }
  if (!order) {
    return json({ error: "That partnership tier is not available online." }, 409, origin);
  }

  const amount = Number(order.amount_ghs);
  const months = Number(order.months);

  // Fire the payment request.
  let moolre;
  try {
    moolre = await moolreCollect(env, { channel, payer, amount, ref, network: input.network });
  } catch {
    await failSponsorRow(env, ref);
    return json({ error: "Payment service unreachable. Please try again." }, 502, origin);
  }

  const code = moolre?.code ? String(moolre.code) : "";
  if (moolre?.status == 1) {
    if (code === "TP14") {
      return json({ ok: true, ref, payer, otp_required: true, amount_ghs: amount, months, tier, message: "otp-required" }, 200, origin);
    }
    return json(
      { ok: true, ref, payer, amount_ghs: amount, months, tier, message: code === "TR099" ? "prompt-sent" : "initiated" },
      200,
      origin
    );
  }

  await failSponsorRow(env, ref);
  return json(
    {
      error: moolre?.message ? String(moolre.message) : "Payment request failed. Please try again.",
      code,
    },
    502,
    origin
  );
}

async function handleSponsorConfirm(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send ref and otp." }, 400, origin);
  }

  const ref = String(input?.ref ?? "").trim();
  const otp = String(input?.otp ?? "").replace(/\s/g, "");
  if (!ref || otp.length < 4) {
    return json({ error: "Enter the full OTP from the SMS." }, 400, origin);
  }

  // Re-submit the amount from our own order row, never the client's.
  let order = null;
  try {
    const res = await sbRpcSigned(env, "get_sponsor_sendable", { p_ref: ref });
    if (res.ok) {
      const rows = await res.json();
      order = Array.isArray(rows) ? rows[0] : null;
    }
  } catch {
    order = null;
  }
  const sponsorConfirmLimited = requireRate(request, "sponsors-confirm", 20, 60_000);
  if (sponsorConfirmLimited) return sponsorConfirmLimited;
  if (!order || !Number.isFinite(Number(order.amount_ghs))) {
    return json({ error: "We could not find that order. Please start again." }, 404, origin);
  }

  const amount = Number(order.amount_ghs);
  const channel = CHANNELS[String(input?.network ?? "").toLowerCase()] ?? "13";
  const payer = normalizeGhPhone(input?.phone) ?? input?.phone;

  let moolre;
  try {
    moolre = await moolreCollect(env, { channel, payer, amount, ref, network: input?.network, otp });
  } catch {
    return json({ error: "Payment service unreachable. Please try again." }, 502, origin);
  }

  const code = moolre?.code ? String(moolre.code) : "";
  if (moolre?.status == 1) {
    return json({ ok: true, ref, message: code === "TR099" ? "prompt-sent" : "initiated" }, 200, origin);
  }

  return json(
    {
      error: moolre?.message ? String(moolre.message) : "Verification failed. Check the code and try again.",
      code,
    },
    400,
    origin
  );
}

// ---------- paid courses (one-time, lifetime access) ----------
// Buying a course requires a signed-in member: the browser's Supabase access
// token is verified here and the resulting uid is what the order is attached
// to, so entitlements can never be attached to someone else's account.
async function handleCourseCharge(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send a course, phone and network." }, 400, origin);
  }

  const courseLimited = requireRate(request, "courses-charge", 10, 60_000);
  if (courseLimited) return courseLimited;
  const courseHuman = await requireHuman(request, env, origin, input);
  if (courseHuman) return courseHuman;

  const courseId = String(input?.course_id ?? "").trim();
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(courseId)) {
    return json({ error: "Pick a course." }, 400, origin);
  }
  const channel = CHANNELS[String(input?.network ?? "").toLowerCase()];
  if (!channel) {
    return json({ error: "Choose MTN, Telecel or AT." }, 400, origin);
  }
  const payer = normalizeGhPhone(input?.phone);
  if (!payer) {
    return json({ error: "Enter a valid 10-digit Ghana phone number." }, 400, origin);
  }

  if (!env.MOOLRE_USER || !env.MOOLRE_PUBKEY || !env.MOOLRE_WALLET) {
    return json({ error: "Online payments are not switched on yet. Please try again later." }, 503, origin);
  }
  if (!env.CONFIRM_SECRET) {
    return json({ error: "Online payments are not switched on yet. Please try again later." }, 503, origin);
  }

  const memberId = await authUserId(env, request);
  if (!memberId) {
    return json({ error: "Please sign in to buy this course.", code: "auth-required" }, 401, origin);
  }

  const ref = `${COURSE_REF_PREFIX}${Date.now().toString(36)}-${crypto.randomUUID().slice(0, 8)}`.toUpperCase();

  // The RPC re-derives the price from courses.price_ghs; the browser never
  // names its own fee.
  let order = null;
  try {
    const res = await sbRpcSigned(env, "create_course_order", {
      p_course_id: courseId,
      p_member_id: memberId,
      p_phone: payer,
      p_network: String(input.network).toLowerCase(),
      p_provider_ref: ref,
    });
    if (res.ok) {
      const rows = await res.json();
      order = Array.isArray(rows) ? rows[0] : null;
    }
  } catch {
    order = null;
  }
  if (!order) {
    return json({ error: "This course can't be purchased right now." }, 409, origin);
  }

  const amount = Number(order.amount_ghs);

  let moolre;
  try {
    moolre = await moolreCollect(env, { channel, payer, amount, ref, network: input.network });
  } catch {
    await failCourseRow(env, ref);
    return json({ error: "Payment service unreachable. Please try again." }, 502, origin);
  }

  const code = moolre?.code ? String(moolre.code) : "";
  if (moolre?.status == 1) {
    if (code === "TP14") {
      return json({ ok: true, ref, payer, otp_required: true, amount_ghs: amount, course_id: courseId, message: "otp-required" }, 200, origin);
    }
    return json(
      { ok: true, ref, payer, amount_ghs: amount, course_id: courseId, message: code === "TR099" ? "prompt-sent" : "initiated" },
      200,
      origin
    );
  }

  await failCourseRow(env, ref);
  return json(
    {
      error: moolre?.message ? String(moolre.message) : "Payment request failed. Please try again.",
      code,
    },
    502,
    origin
  );
}

async function handleCourseConfirm(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send ref and otp." }, 400, origin);
  }

  const ref = String(input?.ref ?? "").trim();
  const otp = String(input?.otp ?? "").replace(/\s/g, "");
  if (!ref || otp.length < 4) {
    return json({ error: "Enter the full OTP from the SMS." }, 400, origin);
  }

  // Re-submit the amount from our own order row, never the client's.
  let order = null;
  try {
    const res = await sbRpcSigned(env, "get_course_sendable", { p_ref: ref });
    if (res.ok) {
      const rows = await res.json();
      order = Array.isArray(rows) ? rows[0] : null;
    }
  } catch {
    order = null;
  }
  const courseConfirmLimited = requireRate(request, "courses-confirm", 20, 60_000);
  if (courseConfirmLimited) return courseConfirmLimited;
  if (!order || !Number.isFinite(Number(order.amount_ghs))) {
    return json({ error: "We could not find that order. Please start again." }, 404, origin);
  }

  const amount = Number(order.amount_ghs);
  const channel = CHANNELS[String(input?.network ?? "").toLowerCase()] ?? "13";
  const payer = normalizeGhPhone(input?.phone) ?? input?.phone;

  let moolre;
  try {
    moolre = await moolreCollect(env, { channel, payer, amount, ref, network: input?.network, otp });
  } catch {
    return json({ error: "Payment service unreachable. Please try again." }, 502, origin);
  }

  const code = moolre?.code ? String(moolre.code) : "";
  if (moolre?.status == 1) {
    return json({ ok: true, ref, message: code === "TR099" ? "prompt-sent" : "initiated" }, 200, origin);
  }

  return json(
    {
      error: moolre?.message ? String(moolre.message) : "Verification failed. Check the code and try again.",
      code,
    },
    400,
    origin
  );
}

async function handleTurnstileVerify(request, env) {
  const origin = request.headers.get("Origin") ?? "";

  let input;
  try {
    input = await request.json();
  } catch {
    return json({ error: "Send a token." }, 400, origin);
  }

  if (!env.TURNSTILE_SECRET) {
    return json({ success: false, error: "turnstile-not-configured" }, 503, origin);
  }

  const token = String(input?.token ?? "").trim();
  if (!token) {
    return json({ error: "Send a token." }, 400, origin);
  }

  const remoteip = String(input?.remoteip ?? "").trim() || (request.headers.get("CF-Connecting-IP") ?? "");

  try {
    const res = await fetch(TURNSTILE_VERIFY, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        secret: env.TURNSTILE_SECRET,
        response: token,
        ...(remoteip ? { remoteip } : {}),
      }),
    });
    const data = await res.json();
    return json({ success: data?.success === true, codes: data?.["error-codes"] ?? [] }, 200, origin);
  } catch {
    return json({ success: false, error: "verify-unreachable" }, 502, origin);
  }
}

async function handleCallback(request, env) {
  const url = new URL(request.url);

  // Shared-secret gate: accepted via header (preferred) or the legacy
  // ?key= query stored in Moolre — random callers can't flip orders either way.
  const key = request.headers.get("x-callback-key") ?? url.searchParams.get("key");
  if (!env.CALLBACK_KEY || key !== env.CALLBACK_KEY) {
    return json({ error: "forbidden" }, 403);
  }
  // M1: Moolre posts from a fixed IP. Enforce it — the key alone in a URL
  // leaks to logs/proxies. GET query callbacks stay accepted (Moolre's own
  // format) but now sit behind the same key + IP gates as POST.
  if (request.headers.get("CF-Connecting-IP") !== MOOLRE_WALLET_CALLBACK_IP) {
    return json({ error: "forbidden" }, 403);
  }

  let body;
  if (request.method === "GET") {
    const q = url.searchParams;
    body = {
      externalref: q.get("externalref") ?? q.get("external_ref") ?? q.get("ref"),
      status: q.get("txstatus") ?? q.get("status"),
      code: q.get("code"),
    };
  } else if (request.method === "POST") {
    const ct = request.headers.get("Content-Type") ?? "";
    try {
      if (ct.includes("form-")) {
        const form = await request.formData();
        const pick = (k) => {
          const v = form.get(k);
          return typeof v === "string" ? v : null;
        };
        body = {
          data: {
            externalref: pick("externalref") ?? pick("external_ref") ?? pick("ref"),
            txstatus: pick("txstatus") ?? pick("status"),
            code: pick("code"),
          },
        };
      } else {
        body = await request.json();
      }
    } catch {
      return json({ error: "bad-json" }, 400);
    }
  } else {
    return json({ error: "method-not-allowed" }, 405);
  }

  const data = body?.data && typeof body.data === "object" ? body.data : {};
  const ref =
    data.externalref ?? data.external_ref ?? body?.externalref ?? body?.external_ref ?? null;
  if (!ref || typeof ref !== "string") {
    return json({ ok: true, ignored: "no-reference" });
  }

  const txstatus = String(data.txstatus ?? data.status ?? body?.status ?? "").toLowerCase();
  const code = String(body?.code ?? data.code ?? "");
  const paid = PAID_SIGNALS.has(txstatus) || code === "P01";
  const failed = FAILED_SIGNALS.has(txstatus);

  // Ambiguous statuses (e.g. still pending) -> acknowledge but change nothing.
  if (!paid && !failed) {
    return json({ ok: true, ignored: "ambiguous-status", ref });
  }
  const finalStatus = paid ? "paid" : "failed";

  // An unrecognised ref cannot be settled against anything. Acknowledge it so
  // Moolre stops retrying instead of 500-ing into a retry storm.
  let kind;
  try {
    kind = orderKind(ref);
  } catch {
    return json({ ok: true, ignored: "unknown-reference", ref });
  }
  const confirmFn = confirmFnFor(kind);

  let settled = false;
  try {
    const res = await sbRpcSigned(env, confirmFn, { p_ref: ref, p_status: finalStatus });
    if (!res.ok) {
      const detail = (await res.text()).slice(0, 200);
      return json({ error: "supabase-update-failed", detail }, 502);
    }
    settled = (await res.json()) === true;

    // Moolre retries callbacks, and this handler is reachable with just the
    // shared key. Send the receipt only when this call is what moved the order
    // from pending, otherwise every retry mails the customer again.
    if (settled && finalStatus === "paid") {
      if (kind === "boost") await sendBoostEmails(env, ref).catch(() => null);
      else if (kind === "sponsor") await sendSponsorEmails(env, ref).catch(() => null);
      else if (kind === "course") await sendCourseEmails(env, ref).catch(() => null);
      else await sendDonationEmails(env, ref).catch(() => null);
    }
  } catch {
    return json({ error: "upstream-error" }, 502);
  }

  return json({
    ok: true,
    ref,
    status: finalStatus,
    settled,
    fromMoolreIp: request.headers.get("CF-Connecting-IP") === MOOLRE_WALLET_CALLBACK_IP,
  });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === "/api/moolre/callback") {
      if (request.method === "GET" || request.method === "POST") {
        return handleCallback(request, env);
      }
      return json({ error: "method-not-allowed" }, 405);
    }

    if (url.pathname === "/api/donations/charge") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleCharge(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/donations/confirm") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleConfirm(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/boosts/charge") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleBoostCharge(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/boosts/confirm") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleBoostConfirm(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/sponsors/charge") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleSponsorCharge(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/sponsors/confirm") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleSponsorConfirm(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/courses/charge") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleCourseCharge(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/courses/confirm") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleCourseConfirm(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/turnstile/verify") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "POST") return handleTurnstileVerify(request, env);
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/api/followup/autoreply") {
      if (request.method !== "POST") return json({ error: "method-not-allowed" }, 405);
      return handleAutoreply(request, env);
    }

    if (url.pathname === "/api/email/test") {
      if (request.method !== "POST") return json({ error: "method-not-allowed" }, 405);
      if (request.headers.get("x-test-key") !== env.EMAIL_TEST_KEY) {
        return json({ error: "forbidden" }, 403);
      }
      const result = await brevoSend(
        env,
        [{ email: "klagonorg@gmail.com", name: "Gideon" }],
        "KlagonOrg worker Brevo test",
        "<p>If you see this, the Cloudflare Worker can send via Brevo.</p>"
      ).catch(() => null);
      return json({ ok: true, result });
    }

    if (url.pathname === "/api/payments/status") {
      const origin = request.headers.get("Origin") ?? "";
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders(origin) });
      }
      if (request.method === "GET" || request.method === "POST") {
        return handlePaymentStatus(request, env);
      }
      return json({ error: "method-not-allowed" }, 405, origin);
    }

    if (url.pathname === "/health") return json({ ok: true });

    return json({ error: "not-found" }, 404);
  },
};