-- ============================================================
-- Marketing consent ledger
--
-- One table records, per person per channel, whether they have agreed
-- to receive marketing by email, SMS or WhatsApp. Every send path must
-- read this before contacting someone; if there is no row, we do not send.
--
-- Default-deny by construction: a missing row means "no permission".
--
-- Append-only. A later row supersedes an earlier one for the same
-- (channel, subject) pair, so revocation is a row with granted = false
-- and nothing is ever erased or overwritten. That leaves a real audit
-- trail, which is what Ghana's Data Protection Act, 2012 (Act 843) and
-- ordinary opt-in regimes both ask for.
--
-- Note the deliberate split from `outreach_suppressions` (STOP replies on
-- WhatsApp cold outreach) — that list is a channel-specific block list for
-- the B2B drive. This table is the affirmative, human-checked permission
-- collected at the point of data entry.
-- ============================================================

create table if not exists public.marketing_consents (
  id bigint generated by default as identity primary key,
  -- 'email' for an address, 'phone' for a mobile number, 'profile' when the
  -- person already has an account and consent is tied to their profile.
  subject_type text not null
    check (subject_type in ('email', 'phone', 'profile')),
  subject_value text not null
    check (length(btrim(subject_value)) > 0),
  channel text not null
    check (channel in ('email', 'sms', 'whatsapp')),
  granted boolean not null,
  -- Which form collected it: footer, contact-form, learning-gate, register, ...
  form_source text not null default 'unknown',
  -- The exact wording version they saw, so a later audit can prove what
  -- was on screen when they ticked. Bump whenever the consent copy changes.
  consent_text_version text not null default '2026-10',
  -- Free-form but bounded: UTM source/medium when we have it.
  context text,
  created_at timestamptz not null default now()
);

create index if not exists marketing_consents_subject_idx
  on public.marketing_consents (subject_type, subject_value, channel, created_at desc);

create index if not exists marketing_consents_created_at_idx
  on public.marketing_consents (created_at desc);

alter table public.marketing_consents enable row level security;

-- Append-only for visitors and members: they may record their own consent
-- and never rewrite or remove it.
--
-- Two things this policy deliberately does not do, stated plainly because an
-- earlier version of this comment claimed otherwise:
--
--   * It does not pair subject_type with subject_value. The column checks
--     above constrain each column on its own; `with check` only re-applies
--     them. The pairing is enforced by marketing_consents_subject_shape,
--     added in 20261009000000_marketing_consents_self_read.sql.
--
--   * It does not check that the subject belongs to the caller. Anonymous
--     sign-ups carry no identity to check against, so recording stays open
--     and this table is an append-only record of a tick rather than proof of
--     who ticked it. Resolve that with double opt-in if the send path ever
--     needs certainty; marketable_subscribers being default-deny is what
--     keeps an unverified row from producing a send on its own.
drop policy if exists "marketing_consents_insert" on public.marketing_consents;
create policy "marketing_consents_insert" on public.marketing_consents
  for insert
  to anon, authenticated
  with check (subject_value is not null and length(btrim(subject_value)) > 0);

-- Deliberately no UPDATE and no DELETE policy for anon/authenticated: rows
-- are permanent, which is what makes the ledger a record rather than a
-- mutable flag. Admins read the whole ledger for compliance queries.
drop policy if exists "marketing_consents_admin_read" on public.marketing_consents;
create policy "marketing_consents_admin_read" on public.marketing_consents
  for select
  to authenticated
  using (is_klagon_admin());

-- ============================================================
-- Consent lookup: "may we message this person on this channel?"
-- Returns the most recent decision, or null when we have never asked
-- them — which callers must treat as no permission.
-- ============================================================
create or replace function public.marketing_consent(
  p_subject_type text,
  p_subject_value text,
  p_channel text
)
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select mc.granted
  from public.marketing_consents mc
  where mc.subject_type = p_subject_type
    and mc.channel = p_channel
    and mc.subject_value = lower(btrim(p_subject_value))
  order by mc.created_at desc, mc.id desc
  limit 1;
$$;

grant execute on function public.marketing_consent(text, text, text) to anon, authenticated;
