-- ============================================================
-- KLAGON WhatsApp outreach + cold-lead CRM (Phase 1 manual)
-- Read-only plugin over DBGABOCHIE snapshots: klagon.org NEVER
-- writes back to the records repo. Local state only:
--   outreach_sends         — tap-to-send log (staff slot, outcome)
--   outreach_suppressions  — STOP / bad-number suppression list
--   lead_captures columns  — CRM status for converted cold leads
-- ============================================================

-- ---------- outreach send log ----------
create table if not exists public.outreach_sends (
  id bigint generated by default as identity primary key,
  source_record_id text not null,
  company text,
  wa_phone text not null,
  staff_slot integer not null default 0,
  template text not null default 'both',
  area text not null default 'standard',
  outcome text not null default 'sent'
    check (outcome in ('sent', 'skipped', 'failed', 'stopped', 'converted')),
  created_at timestamptz not null default now()
);

create index if not exists outreach_sends_phone_idx on public.outreach_sends (wa_phone);
create index if not exists outreach_sends_created_at_idx on public.outreach_sends (created_at desc);

alter table public.outreach_sends enable row level security;

drop policy if exists "outreach_sends_admin_all" on public.outreach_sends;
create policy "outreach_sends_admin_all" on public.outreach_sends
  for all
  to authenticated
  using (is_klagon_admin())
  with check (is_klagon_admin());

-- ---------- suppression list (STOP / bad numbers) ----------
create table if not exists public.outreach_suppressions (
  wa_phone text primary key,
  reason text not null default 'stop'
    check (reason in ('stop', 'bad-number', 'opt-out', 'duplicate')),
  created_at timestamptz not null default now()
);

alter table public.outreach_suppressions enable row level security;

drop policy if exists "outreach_suppressions_admin_all" on public.outreach_suppressions;
create policy "outreach_suppressions_admin_all" on public.outreach_suppressions
  for all
  to authenticated
  using (is_klagon_admin())
  with check (is_klagon_admin());

-- ---------- lead_captures CRM columns for converted cold leads ----------
alter table public.lead_captures
  add column if not exists status text not null default 'new'
    check (status in ('new', 'working', 'converted', 'lost')),
  add column if not exists area text,
  add column if not exists source_record_id text;

create index if not exists lead_captures_status_idx on public.lead_captures (status);
create index if not exists lead_captures_source_record_idx on public.lead_captures (source_record_id);

-- ---------- advance a converted lead (admin only via RLS) ----------
create or replace function public.advance_lead_status(p_id bigint, p_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not is_klagon_admin() then
    raise exception 'admin only';
  end if;
  if p_status not in ('new', 'working', 'converted', 'lost') then
    raise exception 'unknown lead status %', p_status;
  end if;
  update public.lead_captures set status = p_status where id = p_id;
end;
$$;

revoke all on function public.advance_lead_status(bigint, text) from public, anon;
grant execute on function public.advance_lead_status(bigint, text) to authenticated;
