-- ============================================================
-- Post claims + 3-image cap.
--
-- Agents/owners claim org-seeded (or чужой) listings instead of
-- reposting duplicates:
--   post_claims — member files (post, phone) -> admin/super approves
--     -> submitted_by + contact_phone transfer to the claimant,
--     claimable flag removed. Rejection keeps the listing live.
--   gallery cap — cover + gallery combined may never exceed 3 images:
--     gallery jsonb holds at most 2 (cover is the third). Enforced in
--     the DB so no client can smuggle more; PostForm enforces the same
--     total up front.
-- ============================================================

-- ---------- listing ownership claims ----------
create table if not exists public.post_claims (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  claimant_id uuid not null references public.profiles(id) on delete cascade,
  phone text not null,
  note text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  unique (post_id, claimant_id)
);

create index if not exists post_claims_post_idx on public.post_claims (post_id);
create index if not exists post_claims_status_idx on public.post_claims (status);

alter table public.post_claims enable row level security;

-- members file their own claims (must state the number from the advert)
drop policy if exists "post_claims_insert_own" on public.post_claims;
create policy "post_claims_insert_own" on public.post_claims
  for insert to authenticated
  with check (
    claimant_id = auth.uid()
    and char_length(phone) between 9 and 15
  );

-- members see their own; staff see everything
drop policy if exists "post_claims_select_own_or_admin" on public.post_claims;
create policy "post_claims_select_own_or_admin" on public.post_claims
  for select to authenticated
  using (claimant_id = auth.uid() or public.is_admin());

-- moderation is staff-only (admin AND super_admin via is_admin)
drop policy if exists "post_claims_admin_moderate" on public.post_claims;
create policy "post_claims_admin_moderate" on public.post_claims
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---------- max 3 images: cover + gallery(<=2) ----------
-- Gallery arrays longer than 2 are rejected; existing rows are
-- trimmed once so the constraint applies cleanly.
update public.posts
set gallery = (
  select coalesce(jsonb_agg(x.v), '[]'::jsonb)
  from (select v from jsonb_array_elements(gallery) as v limit 2) as x
)
where jsonb_typeof(gallery) = 'array' and jsonb_array_length(gallery) > 2;

alter table public.posts
  drop constraint if exists posts_gallery_max_two;
alter table public.posts
  add constraint posts_gallery_max_two
  check (
    jsonb_typeof(gallery) != 'array' or jsonb_array_length(gallery) <= 2
  );
